language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
before_install:
    - sh scripts/setup_arangodb_travis.sh
install:
    - pip install coverage
    - pip install pytest
    - pip install pytest-cov
    - pip install python-coveralls
    - python setup.py install
script:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 || $TRAVIS_PYTHON_VERSION == 3.4 ]];
      then py.test --cov=arango --ignore=tests/test_asyncio.py;
      else py.test --cov=arango;
      fi
after_success:
    - coveralls
    - pkill -9 -f arango
