sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
services:
    - docker
before_install:
    - docker create --name arango -p 8529:8529 -e ARANGO_ROOT_PASSWORD=passwd arangodb/arangodb:3.7.2 --server.jwt-secret-keyfile=/tmp/keyfile
    - docker cp tests/static/service.zip arango:/tmp/service.zip
    - docker cp tests/static/keyfile arango:/tmp/keyfile
    - docker start arango
install:
    - pip install pytest==4.6.11
    - pip install pytest-cov==2.10.0
    - pip install coveralls==2.0.0
    - pip install mock
    - pip install flake8
    - pip install sphinx sphinx_rtd_theme
    - pip install .
script:
    - python -m flake8
    - python -m sphinx -b doctest docs docs/_build
    - python -m sphinx -b html -W docs docs/_build
    - py.test --complete -s -v --cov=arango
after_success:
    - coveralls
