language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
before_install:
    - sh scripts/setup_arangodb.sh
install:
    - pip install coverage
    - pip install pytest
    - pip install pytest-cov
    - pip install python-coveralls
    - python setup.py install
script:
    - if [[ $TRAVIS_PYTHON_VERSION < 3.5 ]]; then py.test --cov-report= --cov=arango tests/general/; fi
    - if [[$TRAVIS_PYTHON_VERSION >= 3.5 ]]; then py.test --cov-report= --cov=arango tests/general/ tests/py35/; fi
after_success:
    - coveralls
    - pkill -9 -f arango
